Repository TheNoobProgrammeur/birudroid, pull requests merged in 2020-03, with the labels that each got.

#9 📝 Specification de la BDD
  .idea/codeStyles/Project.xml
  .idea/markdown-navigator-enh.xml
  .idea/markdown-navigator.xml
  build.gradle
  doc/spec/database/database_specification.md
  gradle/wrapper/gradle-wrapper.properties
Labels: BDD, Firebase

#14 :pencil: remove collection type beer
  doc/spec/database/database_specification.md
Labels: BDD, Firebase, documentation

#13 Spec/model
  .gitignore
  doc/spec/models/img/beer-detail.png
  doc/spec/models/img/beer.png
  doc/spec/models/img/brand.png
  doc/spec/models/img/brewery.png
  doc/spec/models/img/comment.png
  doc/spec/models/img/model-class.png
  doc/spec/models/img/type-beer.png
  doc/spec/models/img/user.png
  doc/spec/models/spec_model.md
  doc/spec/models/uml/beer-detail.puml
  doc/spec/models/uml/beer.puml
  doc/spec/models/uml/brand.puml
  doc/spec/models/uml/brewery.puml
  doc/spec/models/uml/comment.puml
  doc/spec/models/uml/models-class.puml
  doc/spec/models/uml/type-beer.puml
  doc/spec/models/uml/user.puml
Labels: backend, documentation, kotlin
