Repository TheNoobProgrammeur/birudroid, pull requests merged in 2020-04, with the labels that each got.

#25 Implementation/model/beer
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/berthier/antoine/birudroid/activity/MainActivity.kt
  app/src/main/java/berthier/antoine/birudroid/model/Beer.kt
  app/src/main/java/berthier/antoine/birudroid/model/BeerDetail.kt
  app/src/main/java/berthier/antoine/birudroid/model/Brand.kt
  app/src/main/java/berthier/antoine/birudroid/model/Brewery.kt
  app/src/main/java/berthier/antoine/birudroid/model/Comment.kt
  app/src/main/java/berthier/antoine/birudroid/model/Note.kt
  app/src/main/java/berthier/antoine/birudroid/model/TypeBeer.kt
  app/src/main/java/berthier/antoine/birudroid/model/User.kt
  app/src/main/res/layout/activity_main.xml
  app/src/test/java/berthier/antoine/birudroid/model/BeerDetailTest.kt
  app/src/test/java/berthier/antoine/birudroid/model/BeerTest.kt
  app/src/test/java/berthier/antoine/birudroid/model/BrandTest.kt
  app/src/test/java/berthier/antoine/birudroid/model/BreweryTest.kt
  app/src/test/java/berthier/antoine/birudroid/model/CommentTest.kt
  app/src/test/java/berthier/antoine/birudroid/model/UserTest.kt
Labels: backend, kotlin

#28 :pencil: refacto specs bdd
  doc/scenarios/01-inscription.md
  doc/scenarios/02-connexion.md
  doc/scenarios/06-filter-des-bieres.md
  doc/spec/database/database_specification.md
Labels: BDD, Firebase, documentation

#35 :pencil: modif scenario 11
  doc/scenarios/11-ajouter-biere.md
Labels: documentation

#27 📄 Adding license.
  Licence
  README.md
Labels: Licence

#47 🚧 Add IdImmageBeer
  app/src/main/java/berthier/antoine/birudroid/model/Beer.kt
  app/src/main/java/berthier/antoine/birudroid/model/BeerDetail.kt
Labels: backend, kotlin
